# Generated by Django 3.2.16 on 2022-10-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('password', models.CharField(max_length=240, verbose_name='Password')),
                ('surname', models.CharField(max_length=240, verbose_name='Surname')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('birthdate', models.DateField(verbose_name='Birth Date')),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),

            ],
        ),
    ]
