# Generated by Django 3.2.16 on 2022-10-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20221011_2307'),
    ]

    operations = [
    ]
