# Generated by Django 3.2.16 on 2022-10-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_failedloginattemps'),
    ]

    operations = [
    ]
